const products = [
  {
    id: 1,
    name: "Butter",
    category: "Lunch",
    description: "Butter is a soft, creamy dairy product made from milk or cream.  ",
    price: 89,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/1.png",
      // "../assets/images/products/2.png",
      // "../assets/images/products/3.png",
      // "../assets/images/products/4.png",
    ],
  },
  {
    id: 2,
    name: "Coffee",
    category: "Dessert",
    description:
      "Coffee is a dark, aromatic drink made from roasted coffee beans.",
    price: 71,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/2.png",
      // "../assets/images/products/3.png",
      // "../assets/images/products/4.png",
      // "../assets/images/products/5.png",
    ],
  },
  {
    id: 3,
    name: "Sausage",
    category: "Lunch",
    description:
      "Sausage is a food made from ground meat mixed with spices and often cooked",
    price: 88,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/3.png",
      // "../assets/images/products/4.png",
      // "../assets/images/products/5.png",
      // "../assets/images/products/6.png",
    ],
  },
  {
    id: 4,
    name: "Pomegranate",
    category: "Fruit",
    description:
      "Pomegranate is a healthy fruit.It is rich in vitamins and very good for health.",
    price: 94,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/4.png",
      // "../assets/images/products/5.png",
      // "../assets/images/products/6.png",
      // "../assets/images/products/7.png",
    ],
  },
  {
    id: 5,
    name: "Raspberry",
    category: "Fruit",
    description:
      "Raspberry is a small red fruit made up of many tiny juicy parts. ",
    price: 82,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/5.png",
      // "../assets/images/products/6.png",
      // "../assets/images/products/7.png",
      // "../assets/images/products/8.png",
    ],
  },
  {
    id: 6,
    name: "Strawberry",
    category: "Fruit",
    description:
      "Strawberry is a small red fruit with a sweet taste and tiny seeds on its surface.",
    price: 91,
    rating: 3.5,
    discount: 50,
    images: [
      "../assets/images/products/6.png",
      // "../assets/images/products/7.png",
      // "../assets/images/products/8.png",
      // "../assets/images/products/9.png",
    ],
  },
  {
    id: 7,
    name: "Cake",
    category: "Dessert",
    description:
      "Cake is a sweet, soft dessert made from flour, sugar, eggs, and butter.",
    price: 68,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/7.png",
      // "../assets/images/products/8.png",
      // "../assets/images/products/9.png",
      // "../assets/images/products/10.png",
    ],
  },
  {
    id: 8,
    name: "Chocolate",
    category: "Dessert",
    description:
      "A sweet food made from cacao beans, used in a variety of desserts and confections.",
    price: 61,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/32.png",
      "../assets/images/products/9.png",
      "../assets/images/products/10.png",
      "../assets/images/products/11.png",
    ],
  },
  {
    id: 9,
    name: "Coffee",
    category: "Dessert",
    description:
      "A dark, bitter beverage made from roasted coffee beans, typically used as a pick-me-up.",
    price: 98,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/30.png",
      "../assets/images/products/29.png",
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
    ],
  },
  {
    id: 10,
    name: "Cheese",
    category: "Dairy",
    description:
      "A dairy product made from milk, with a variety of textures and flavors.",
    price: 79,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/10.png",
      // "../assets/images/products/11.png",
      // "../assets/images/products/12.png",
      // "../assets/images/products/13.png",
    ],
  },
  {
    id: 11,
    name: "Fish",
    category: "Meat",
    description:
      "A type of seafood, known for its omega-3 fatty acids and high protein content.",
    price: 89,
    rating: 3.5,
    discount: 50,
    images: [
      "../assets/images/products/27.png",
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
    ],
  },
  {
    id: 12,
    name: "Kebab",
    category: "Dinner",
    description:
      "Kebab is a popular dish made of grilled meat, often served on skewers.",
    price: 61,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/12.png",
      // "../assets/images/products/13.png",
      // "../assets/images/products/14.png",
      // "../assets/images/products/15.png",
    ],
  },
  {
    id: 13,
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/13.png",
      // "../assets/images/products/14.png",
      // "../assets/images/products/15.png",
      // "../assets/images/products/16.png",
    ],
  },
  {
    id: 14,
    name: "Yogurt",
    category: "Dessert",
    description:
      "Yogurt is a creamy dairy product made from fermented milk.",
    price: 84,
    rating: 4.5,
    discount: 50,
    images: [
      "../assets/images/products/14.png",
      // "../assets/images/products/15.png",
      // "../assets/images/products/16.png",
      // "../assets/images/products/17.png",
    ],
  },
  {
    id: 15,
    name: "Yogurt",
    category: "Dessert",
    description:
      "Yogurt is a creamy dairy product made from fermented milk.",
    price: 68,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/15.png",
      // "../assets/images/products/16.png",
      // "../assets/images/products/17.png",
      // "../assets/images/products/18.png",
    ],
  },
  {
    id: 16,
    name: "Orange",
    category: "Fruit",
    description:
      "It is rich in vitamin C and helps strengthen the immune system.",
    price: 74,
    rating: 3.5,
    discount: 0,
    images: [
      "../assets/images/products/16.png",
      // "../assets/images/products/17.png",
      // "../assets/images/products/18.png",
      // "../assets/images/products/19.png",
    ],
  },
  {
    id: 17,
    name: "Apple",
    category: "Fruit",
    description:
      "A round fruit with a red, green, or yellow",
    price: 70,
    rating: 4.5,
    discount: 50,
    images: [
      "../assets/images/products/17.png",
      // "../assets/images/products/18.png",
      // "../assets/images/products/19.png",
      // "../assets/images/products/20.png",
    ],
  },
  {
    id: 18,
    name: "Bread",
    category: "Bakery",
    description:
      "Bread is a common food made from flour, water, and yeast.",
    price: 87,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/18.png",
      // "../assets/images/products/19.png",
      // "../assets/images/products/20.png",
      // "../assets/images/products/21.png",
    ],
  },
  {
    id: 19,
    name: "Coca Cola",
    category: "Drink",
    description:
      "Cola is a sweet, carbonated drink with a strong, refreshing taste.",
    price: 83,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/19.png",
      // "../assets/images/products/20.png",
      // "../assets/images/products/21.png",
      // "../assets/images/products/22.png",
    ],
  },
  {
    id: 20,
    name: "Kebab",
    category: "Dinner",
    description:
      "Kebab is a popular dish made of grilled meat, often served on skewers. ",
    price: 76,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/20.png",
      // "../assets/images/products/21.png",
      // "../assets/images/products/22.png",
      // "../assets/images/products/23.png",
    ],
  },
  {
    id: 21,
    name: "Juice",
    category: "Fruit",
    description:
      "Juice is a sweet liquid made from fresh fruits or vegetables.",
    price: 77,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/21.png",
      // "../assets/images/products/22.png",
      // "../assets/images/products/23.png",
      // "../assets/images/products/24.png",
    ],
  },
  {
    id: 22,
    name: "Banana",
    category: "Fruit",
    description:
      "Banana is a long yellow fruit with soft, sweet flesh inside. ",
    price: 80,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/22.png",
      // "../assets/images/products/23.png",
      // "../assets/images/products/24.png",
      // "../assets/images/products/25.png",
    ],
  },
  {
    id: 23,
    name: "Juice",
    category: "Drink",
    description:
      "Juice is a sweet liquid made from fresh fruits or vegetables.",
    price: 93,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/23.png",
      // "../assets/images/products/24.png",
      // "../assets/images/products/25.png",
      // "../assets/images/products/26.png",
    ],
  },
  {
    id: 24,
    name: "Pizza",
    category: "Lunch",
    description:
      "Pizza is a popular dish made from dough, sauce, cheese, and toppings.",
    price: 94,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/24.png",
      // "../assets/images/products/25.png",
      // "../assets/images/products/26.png",
      // "../assets/images/products/27.png",
    ],
  },
  {
    id: 25,
    name: "Orange",
    category: "Fruit",
    description:
      "It is rich in vitamin C and helps strengthen the immune system.",
    price: 71,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/25.png",
      // "../assets/images/products/26.png",
      // "../assets/images/products/27.png",
      // "../assets/images/products/28.png",
    ],
  },
  {
    id: 26,
    name: "Apricot",
    category: "Fruit",
    description:
      "Apricot is a small orange fruit with soft, sweet flesh and a single seed inside.",
    price: 63,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/26.png",
      // "../assets/images/products/27.png",
      // "../assets/images/products/28.png",
      // "../assets/images/products/29.png",
    ],
  },
  {
    id: 27,
    name: "Fish",
    category: "Dinner",
    description:
      "Fish is a healthy food rich in protein and omega-3 fatty acids",
    price: 97,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/27.png",
      // "../assets/images/products/28.png",
      // "../assets/images/products/29.png",
      // "../assets/images/products/30.png",
    ],
  },
  {
    id: 28,
    name: "Pineapple",
    category: "Fruit",
    description:
      "Pineapple is a tropical fruit with spiky skin and sweet, juicy yellow flesh.",
    price: 81,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/28.png",
      // "../assets/images/products/29.png",
      // "../assets/images/products/30.png",
      // "../assets/images/products/31.png",
    ],
  },
  {
    id: 29,
    name: "Coffee",
    category: "Dessert",
    description:
      "Coffee is a dark, aromatic drink made from roasted coffee beans.",
    price: 96,
    rating: 3,
    discount: 50,
    images: [
      "../assets/images/products/29.png",
      // "../assets/images/products/30.png",
      // "../assets/images/products/31.png",
      // "../assets/images/products/32.png",
    ],
  },
  {
    id: 30,
    name: "Pizza",
    category: "Lunch",
    description:
      "Pizza is a popular dish made from dough, sauce, cheese, and toppings.",
    price: 95,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/24.png",
      // "../assets/images/products/31.png",
      // "../assets/images/products/32.png",
      // "../assets/images/products/33.png",
    ],
  },
  {
    id: 31,
    name: "Milk",
    category: "Dairy",
    description:
      "Milk is a white liquid rich in calcium, protein and keep the body healthy.",
    price: 100,
    rating: 5,
    discount: 50,
    images: [
      "../assets/images/products/31.png",
      // "../assets/images/products/32.png",
      // "../assets/images/products/33.png",
      // "../assets/images/products/34.png",
    ],
  },
  {
    id: 32,
    name: "Dark Chocolate",
    category: "Dessert",
    description:
      "Dark chocolate is a rich, slightly bitter treat made from cocoa beans.",
    price: 63,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/32.png",
      // "../assets/images/products/33.png",
      // "../assets/images/products/34.png",
      // "../assets/images/products/35.png",
    ],
  },
  {
    id: 33,
    name: "Pumkin",
    category: "Vegetable",
    description:
      "Pumpkin is a round vegetable with orange skin and soft, sweet flesh inside. ",
    price: 82,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/33.png",
      // "../assets/images/products/34.png",
      // "../assets/images/products/35.png",
      // "../assets/images/products/36.png",
    ],
  },
  {
    id: 34,
    name: "Kiwi",
    category: "Fruit",
    description:
      "Kiwi is a small brown fruit with green, juicy flesh and tiny black seeds.",
    price: 94,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/34.png",
      // "../assets/images/products/35.png",
      // "../assets/images/products/36.png",
      // "../assets/images/products/1.png",
    ],
  },
  {
    id: 35,
    name: "Pomegranate",
    category: "Fruit",
    description:
      "Pomegranate is a healthy fruit.It is rich in vitamins and very good for health.",
    price: 70,
    rating: 1,
    discount: 0,
    images: [
      "../assets/images/products/35.png",
      // "../assets/images/products/36.png",
      // "../assets/images/products/1.png",
      // "../assets/images/products/2.png",
    ],
  },
  {
    id: 36,
    name: "Melon",
    category: "Fruit",
    description:
      "Melon is a sweet and juicy fruit with yellow or green skin and soft flesh inside.",
    price: 98,
    rating: 3.5,
    discount: 0,
    images: [
      "../assets/images/products/36.png",
      // "../assets/images/products/1.png",
      // "../assets/images/products/2.png",
      // "../assets/images/products/3.png",
    ],
  },
];
